### ISSUE TITLE
Missing packages + invalid property name

### ISSUE THREAD

**Issue by xnuinside** [Lionad-Morotar/toast-ui-calendar-vue3#2]
### Describe the bug

Hi! First and foremost, a huge thank you for sharing your code. It has been incredibly helpful to me. I just wanted to report an issue that arises when following your tutorial step-by-step; there are missing packages.

<img width="878" alt="Screenshot 2023-10-30 at 15 24 56" src="https://github.com/Lionad-Morotar/toast-ui-calendar-vue3/assets/15959809/ade4cfbb-9236-4989-8b47-9607892ad67a">

Of course, the issue can be easily resolved with `pnpm add element-plus` and `pnpm add vxe-table`, but I'm uncertain if these libraries should be added as project dependencies in the repository.

If they aren't necessary for some reason, please feel free to close this issue. And once again, thank you!

+ property name in events is incorrect i`sReadonly` should be `isReadOnly` - here  https://github.com/Lionad-Morotar/toast-ui-calendar-vue3/blob/dev/play/src/mock-data.js#L16C5-L16C15 and here https://github.com/Lionad-Morotar/toast-ui-calendar-vue3/blob/dev/play/src/mock-data.js#L25

### Steps to reproduce

In totally new env after git clone:

1. `pnpm install`
2. `pnpm serve`

### Environment Info

```shell
MacOs
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Readme](https://github.com/Lionad-Morotar/toast-ui-calendar-vue3).
- [X] Check that there isn't [already an issue](https://github.com/Lionad-Morotar/toast-ui-calendar-vue3/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Lionad-Morotar/toast-ui-calendar-vue3/discussions).

**Comment by Lionad-Morotar** [comment]
Aha, thanks a lot~ I'll fix that !

`element-plus` and `vxe-table` is useless deps but imported on `playground/main.ts`
